name: Continuous Integration

on:
    push:

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checking out sources
              uses: actions/checkout@v3
            - name: Installing Rust toolchain
              run: rustup toolchain install stable
            - uses: Swatinem/rust-cache@v2
            - name: Checking formatting
              run: cargo fmt --check
            - name: Checking lints
              run: cargo clippy --all-targets -- -D warnings
            - name: Checking doc references
              uses: Icelk/rustdoc-link-check@v1
              with:
                  private: true
            - name: Testing project
              run: cargo test
